spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    open-in-view: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    lease-renewal-interval-in-seconds: 3

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.microservice.store.product.api: debug

server:
  port: ${PORT:8401}

feign:
  client:
    config:
      default:
        read-timeout: 1000
        connect-timeout: 1000
  sentinel:
    enabled: true




